### ISSUE TITLE
java.lang.module.ResolutionException 怎么解决

### ISSUE THREAD

**Issue by lololololkl** [ct437383389/DesktopSubtitles#1]
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules javax.websocket.api and tyrus.standalone.client export package javax.websocket to module javafx.webEmpty

**Comment by ch3nnn** [comment]
是不是使用了jdk8运行的,  需要jdk11运行项目

**Comment by lololololkl** [comment]
> 是不是使用了jdk8运行的, 需要jdk11运行项目

![image](https://user-images.githubusercontent.com/39233442/163741153-608b543b-4ff2-4208-95c6-e2349e2bc5da.png)
用的jdk11

**Comment by ch3nnn** [comment]
是否因为 pom.xml 文件 tyrus-standalone-client 和 javax.websocket-api 这两个依赖版本有关系 ,  我的jdk11.0.10 是可以运行的

**Comment by lololololkl** [comment]
> 是否因为 pom.xml 文件 tyrus-standalone-client 和 javax.websocket-api 这两个依赖版本有关系 , 我的jdk11.0.10 是可以运行的

thanks，好
